blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://stackoverflow.com/questions/tagged/rebased
    about: This is a bug tracker, not a support system. For usage questions, please use our support resources.
