name: cache
'on':
  push:
    branches:
      - master
    paths:
      - 'packages/cache/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run cache tests
        run: cd ./packages/cache && npm test
      - name: Upload cache coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./packages/cache/coverage
          fail_ci_if_error: true
          name: cache
          verbose: true
