name: docs
'on':
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run code coverage badges
        run: npm run coverage
      - name: Run changelog
        run: npm run changelog
      - name: Install docs modules
        run: cd ./docs && npm ci
      - name: Run build
        run: cd ./docs && npm run generate
      - name: Deploy docs
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiKey: ${{ secrets.CF_API_KEY }}
          email: ${{ secrets.CF_EMAIL }}
          workingDirectory: docs
