name: docs
'on':
  push:
    branches:
      - master
    paths:
      - 'packages/**'
      - 'docs/**'
      - 'workflows/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run code coverage badges
        run: npm run coverage
      - name: Install docs modules
        run: cd ./docs && npm ci
      # - name: Run changelog and build
      #   run: npm run changelog && cd ./docs && npm run generate
      - name: Build docs
        run: cd ./docs && npm run generate
      - name: Deploy docs
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: docs
