# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

#
# on:
#   push:
#     paths:
#       - 'libs/core/*'

jobs:
  build:
    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Deps Install
        run: npm install -f
      - name: Core Lint
        run: ./node_modules/.bin/ng lint core
      - name: Core Build
        run: ./node_modules/.bin/ng build core --prod
      - name: Core Test
        run: ./node_modules/.bin/ng test core --configuration=ci
