name: parse
'on':
  push:
    branches:
      - master
    paths:
      - 'packages/parse/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run parse tests
        run: cd ./packages/parse && npm test
      - name: Upload parse coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./packages/parse/coverage
          fail_ci_if_error: true
          name: parse
          verbose: true
