name: state
'on':
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run state tests
        run: cd ./packages/state && npm test
      - name: Upload state coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./packages/state/coverage
          fail_ci_if_error: true
          name: state
          verbose: true
